import {
  Body,
  Button,
  Column,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Img,
  Link,
  Preview,
  Row,
  Section,
  Text,
} from '@react-email/components';
import { Tailwind } from '@react-email/components';

interface AnalysisNotificationEmailProps {
  username: string;
  userImage?: string;
  certificationName?: string;
  readinessScore?: number;
}

const baseUrl = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : 'https://www.clouddojo.tech';

export const AnalysisNotificationEmail = ({
  username = 'there',
  userImage,
  certificationName = 'AWS Certification',
  readinessScore,
}: AnalysisNotificationEmailProps) => {
  const previewText = `Your AWS Certification AI Analysis is ready!`;

  return (
    <Html>
      <Head />
      <Tailwind>
        <Body className="mx-auto my-auto bg-white px-2 font-sans">
          <Preview>{previewText}</Preview>
          <Container className="mx-auto my-[40px] max-w-[465px] rounded border border-emerald-200 border-solid p-[20px]">
            <Section className="mt-[32px]">
              <Img
                src={`https://www.clouddojo.tech/images/dojo-logo.png`}
                width="40"
                height="40"
                alt="CloudDojo Logo"
                className="mx-auto my-0"
              />
            </Section>
            <Heading className="mx-0 my-[30px] p-0 text-center font-normal text-[24px] text-black">
              Your <strong className="text-emerald-600">AI Analysis</strong> is Ready
            </Heading>
            <Text className="text-[14px] text-black leading-[24px]">
              Hello {username},
            </Text>
            <Text className="text-[14px] text-black leading-[24px]">
              Your latest AWS certification practice analysis has been generated by CloudDojo AI. We've analyzed your recent performance and prepared detailed insights to help you succeed.
            </Text>
            <Section className="my-[32px] text-center">
              <Button
                className="rounded bg-emerald-600 px-6 py-3 text-center font-semibold text-[14px] text-white no-underline hover:bg-emerald-700"
                href="https://www.clouddojo.tech/dashboard"
              >
                View Your Analysis
              </Button>
            </Section>
            <Section className="mb-[32px]">
              <Row>
                <Column className="px-2">
                  <div className="rounded-lg border border-gray-200 p-4 text-center">
                    <Text className="m-0 text-[12px] text-gray-500">Study Progress</Text>
                    <Text className="m-0 text-[18px] font-bold text-emerald-600">Daily Update</Text>
                  </div>
                </Column>
                <Column className="px-2">
                  <div className="rounded-lg border border-gray-200 p-4 text-center">
                    <Text className="m-0 text-[12px] text-gray-500">AI-Powered</Text>
                    <Text className="m-0 text-[18px] font-bold text-emerald-600">Insights</Text>
                  </div>
                </Column>
              </Row>
            </Section>
            <Text className="text-[14px] text-black leading-[24px]">
              Your analysis includes:
            </Text>
            <ul className="list-none pl-0">
              <li className="text-[14px] text-black leading-[24px] mb-2">✓ Certification readiness tracking</li>
              <li className="text-[14px] text-black leading-[24px] mb-2">✓ Areas for improvement</li>
              <li className="text-[14px] text-black leading-[24px] mb-2">✓ Personalized study recommendations</li>
            </ul>
            <Hr className="mx-0 my-[26px] w-full border border-gray-200 border-solid" />
            <Text className="text-[#666666] text-[12px] leading-[24px]">
              This analysis is automatically generated every 24 hours to help you stay on track with your AWS certification goals. If you have any questions, please don't hesitate to reach out to our support team.
            </Text>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
};

export default AnalysisNotificationEmail; 